# Name for the github action
name: Push to Master

# Trigger this action when we push to master or merge a pull-request to master
on:
  push:
      branches:
        - master
      paths:
        - package.json
  workflow_dispatch:
  

# runs the jobs
jobs:

  build:
      # runs on ubuntu
      runs-on: ubuntu-latest
  
      steps:
        # checkout to github
        - uses: actions/checkout@v2
        - name: Run tests
          uses: ./.github/workflows/main.yml  # use the callable tests job to run tests
          with:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # semantic release action from third party
        - name: Semantic release
          uses: codfish/semantic-release-action@master
      # Add the environment variable for NPM and github. Github is needed because semantic-release will create a new release and release notes automatically
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}